import { Column } from "@/types/table.type";

export const STUDENT_TABLE_COLUMNS: Column[] = [
    {
        id: "id",
        label: "المعرف",
        type: "number",
        accessor: "id",
        editable: false,
        sortable: true,
        filterable: true,
        filterMode: "popover",
        // Server operations
        // serverSortable: true,
        // serverFilterable: true,
    },
    {
        id: "name",
        label: "الاسم",
        type: "text",
        accessor: "name",
        editable: true,
        sortable: true,
        filterable: true,
        filterMode: "popover",
        // Server operations
        serverSortable: true,
        serverFilterable: true,
        widthStorageKey: "student_table_student_name_column_width",
    },
    {
        id: "email",
        label: "البريد الإلكتروني",
        type: "text",
        accessor: "email",
        editable: true,
        sortable: true,
        filterable: true,
        filterMode: "popover",
        // Server operations
        serverSortable: true,
        serverFilterable: true,
        widthStorageKey: "student_table_student_email_column_width",
    },
    {
        id: "date_of_birth",
        label: "تاريخ الميلاد",
        type: "date",
        accessor: "date_of_birth",
        editable: true,
        sortable: true,
        filterable: true,
        filterMode: "popover",
        // Server operations
        serverSortable: true,
        serverFilterable: true,
        widthStorageKey: "student_table_student_date_of_birth_column_width",
    },
    {
        id: "gender",
        label: "الجنس",
        type: "text",
        accessor: "gender",
        editable: true,
        sortable: true,
        filterable: true,
        filterMode: "popover",
        // Server operations
        serverSortable: true,
        serverFilterable: true,
        widthStorageKey: "student_table_student_gender_column_width",
    },
    {
        id: "nationality",
        label: "الجنسية",
        type: "text",
        accessor: "nationality",
        editable: true,
        sortable: true,
        filterable: true,
        filterMode: "popover",
        // Server operations
        serverSortable: true,
        serverFilterable: true,
        widthStorageKey: "student_table_student_nationality_column_width",
    },
    {
        id: "phone_number",
        label: "رقم الهاتف",
        type: "text",
        accessor: "phone_number",
        sortable: false,
        filterable: true,
        editable: true,
        filterMode: "popover",
        // Server operations
        serverSortable: true,
        serverFilterable: true,
        widthStorageKey: "student_table_student_phone_number_column_width",
    },
    {
        id: "created_at",
        label: "تاريخ الإضافة",
        type: "date",
        accessor: "created_at",
        sortable: true,
        filterable: true,
        editable: false,
        filterMode: "popover",
        // Server operations
        serverSortable: true,
        serverFilterable: true,
        widthStorageKey: "student_table_student_created_at_column_width",
    },
    {
        id: "updated_at",
        label: "تاريخ التحديث",
        type: "date",
        accessor: "updated_at",
        sortable: true,
        filterable: true,
        editable: false,
        filterMode: "popover",
        // Server operations
        serverSortable: true,
        serverFilterable: true,
        widthStorageKey: "student_table_student_updated_at_column_width",
    },
];
