// This is a build script to be run with Node.js (e.g., using ts-node)
// It reads the Google Fonts JSON and generates typed subset files.

import * as fs from "fs";
import * as path from "path";
// Assumes this script is at the project root, importing from the client dir
import { processFontList, GoogleFontItem } from "./types";
import { logger } from "../simpleLogger";

// --- Configuration ---
// Define all the paths based on the project root
const SUBSET_DIR = path.resolve(__dirname, "lib/font/google/subset");
const GOOGLE_FONT_DIR = path.resolve(__dirname, "lib/font/google");
const TYPES_FILE_PATH = path.resolve(
  GOOGLE_FONT_DIR,
  "google-font-subset-map.type.ts"
);
const CONST_FILE_PATH = path.resolve(
  GOOGLE_FONT_DIR,
  "google-font-subset-map.const.ts"
);

// Relative import paths for use inside the generated files
const TYPES_IMPORT_PATH = "./types"; // Relative path from GOOGLE_FONT_DIR to types.ts
const SUBSET_IMPORT_PATH = "./subset"; // Relative path from GOOGLE_FONT_DIR to subset dir

// --- Helper Functions ---

/**
 * Sanitizes a subset name (e.g., "latin-ext") into a valid JS variable name (e.g., "latinExt").
 * This is crucial for creating valid import statements.
 */
function sanitizeSubsetForVar(name: string): string {
  // Replaces non-alphanumeric characters with a space, then camelCases
  return name
    .replace(/[^a-zA-Z0-9_]/g, " ")
    .split(" ")
    .map((part, index) => {
      if (!part) return "";
      if (index === 0) return part.toLowerCase();
      return part.charAt(0).toUpperCase() + part.slice(1).toLowerCase();
    })
    .join("");
}

/**
 * Creates a file, ensuring the directory exists first.
 */
function writeFile(filePath: string, content: string): void {
  try {
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) {
      // Create the directory recursively if it doesn't exist
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(filePath, content, "utf-8");
    logger.log(`✅ Successfully wrote: ${path.basename(filePath)}`);
  } catch (error) {
    logger.error(`❌ Error writing file ${filePath}:`, error);
  }
}

// --- File Content Generators ---

/**
 * Generates the content for a single subset file (e.g., latin.ts).
 */
function createSubsetFileContent(fontItems: GoogleFontItem[]): string {
  // Relative path from lib/font/google/subset/ to lib/font/google/types.ts
  const importPath = "../types";
  // Stringify the array of font items
  const data = JSON.stringify(fontItems, null, 2);

  return `// This file is auto-generated by generate-font-subsets.ts
/* eslint-disable */
import { GoogleFontItem } from '${importPath}';

const data: GoogleFontItem[] = ${data};

export default data;
`;
}

/**
 * Generates the content for the main type file (google-font-subset-map.type.ts).
 */
function createTypeFileContent(subsetKeys: string[]): string {
  // Create a type entry for each subset key
  const typeEntries = subsetKeys
    .map(key => `  '${key}': GoogleFontItem[];`)
    .join("\n");

  return `// This file is auto-generated by generate-font-subsets.ts
/* eslint-disable */
import { GoogleFontItem } from '${TYPES_IMPORT_PATH}';

export type GoogleFontSubsetMap = {
${typeEntries}
};
`;
}

/**
 * Generates the content for the main const file (google-font-subset-map.const.ts).
 */
function createConstFileContent(subsetKeys: string[]): string {
  // Create an import statement for each subset file
  const imports = subsetKeys
    .map(key => {
      const varName = sanitizeSubsetForVar(key);
      const filePath = `${SUBSET_IMPORT_PATH}/${key}`;
      return `import ${varName} from '${filePath}';`;
    })
    .join("\n");

  // Create the key-value pairs for the const object
  const constEntries = subsetKeys
    .map(key => {
      const varName = sanitizeSubsetForVar(key);
      return `  '${key}': ${varName},`;
    })
    .join("\n");

  return `// This file is auto-generated by generate-font-subsets.ts
/* eslint-disable */
import { GoogleFontSubsetMap } from './google-font-subset-map.type';
${imports}

export const googleFontSubsetMap: GoogleFontSubsetMap = {
${constEntries}
};
`;
}

// --- Main Function ---

/**
 * Receives the Google Fonts JSON response as a string, processes it,
 * and generates all necessary subset files and type definitions.
 *
 * @param jsonString The raw JSON string from the Google Fonts API.
 */
export function generateFontSubsetFiles(jsonString: string) {
  logger.log("Starting font subset file generation...");

  // 1. Process the raw string into the map
  const subsetMap = processFontList(jsonString);
  // Get all unique subset names and sort them for consistent file order
  const subsetKeys = Array.from(subsetMap.keys()).sort();

  if (subsetKeys.length === 0) {
    logger.warn(
      "⚠️ No subsets found in the provided JSON. No files will be generated."
    );
    return;
  }

  // 2. Generate and write all individual subset files
  logger.log(
    `Found ${subsetKeys.length} subsets. Generating subset files in ${SUBSET_DIR}...`
  );
  for (const [subsetName, fontItems] of subsetMap.entries()) {
    const subsetFilePath = path.resolve(SUBSET_DIR, `${subsetName}.ts`);
    const fileContent = createSubsetFileContent(fontItems);
    writeFile(subsetFilePath, fileContent);
  }

  // 3. Generate and write the main type file
  logger.log(`Generating type file: ${TYPES_FILE_PATH}...`);
  const typeFileContent = createTypeFileContent(subsetKeys);
  writeFile(TYPES_FILE_PATH, typeFileContent);

  // 4. Generate and write the main const file
  logger.log(`Generating const file: ${CONST_FILE_PATH}...`);
  const constFileContent = createConstFileContent(subsetKeys);
  writeFile(CONST_FILE_PATH, constFileContent);

  logger.log("\n🎉 Font subset file generation complete.");
}

// --- Example Usage ---
// To run this script:
// 1. Make sure you have 'ts-node' installed (e.g., `npm install -g ts-node`)
// 2. Place `google_fonts.json` in the same directory as this script (the project root).
// 3. Run it from your project root:
//    ts-node ./generate-font-subsets.ts

// This block automatically runs the function if the script is executed directly
try {
  // Assumes google_fonts.json is at the project root
  const fontJsonPath = path.resolve(__dirname, "google_fonts.json");
  if (fs.existsSync(fontJsonPath)) {
    logger.log("Found 'google_fonts.json', starting generation...");
    const jsonString = fs.readFileSync(fontJsonPath, "utf-8");
    generateFontSubsetFiles(jsonString);
  } else {
    logger.warn(
      "⚠️ 'google_fonts.json' not found at project root. Script will not run automatically."
    );
    logger.log(
      "You can still import 'generateFontSubsetFiles' and run it manually."
    );
  }
} catch (error) {
  logger.error("❌ Failed to read 'google_fonts.json'.", error);
}
