// This file is auto-generated by generateFontSubsetFiles.ts
import { GoogleFontItem } from '../types';

const data: GoogleFontItem[] = [
  {
    "family": "Noto Sans Brahmi",
    "variants": [
      "regular"
    ],
    "subsets": [
      "brahmi",
      "latin",
      "latin-ext",
      "math",
      "symbols"
    ],
    "version": "v20",
    "lastModified": "2025-09-10",
    "files": {
      "regular": "https://fonts.gstatic.com/s/notosansbrahmi/v20/vEFK2-VODB8RrNDvZSUmQQIIByV18tK1W77HtMo.ttf"
    },
    "category": "sans-serif",
    "kind": "webfonts#webfont",
    "menu": "https://fonts.gstatic.com/s/notosansbrahmi/v20/vEFK2-VODB8RrNDvZSUmQQIIByV1wtO_Xw.ttf"
  }
];

export default data;
