// This file is auto-generated by generateFontSubsetFiles.ts
import { GoogleFontItem } from '../types';

const data: GoogleFontItem[] = [
  {
    "family": "Noto Sans Chakma",
    "variants": [
      "regular"
    ],
    "subsets": [
      "chakma",
      "latin",
      "latin-ext"
    ],
    "version": "v18",
    "lastModified": "2025-09-05",
    "files": {
      "regular": "https://fonts.gstatic.com/s/notosanschakma/v18/Y4GQYbJ8VTEp4t3MKJSMjg5OIzhi4JjTQhYBeYo.ttf"
    },
    "category": "sans-serif",
    "kind": "webfonts#webfont",
    "menu": "https://fonts.gstatic.com/s/notosanschakma/v18/Y4GQYbJ8VTEp4t3MKJSMjg5OIzhi0JnZRg.ttf"
  }
];

export default data;
