// This file is auto-generated by generateFontSubsetFiles.ts
import { GoogleFontItem } from '../types';

const data: GoogleFontItem[] = [
  {
    family: "Noto Sans Glagolitic",
    variants: [
      "regular"
    ],
    subsets: [
      "cyrillic-ext",
      "glagolitic",
      "latin",
      "latin-ext",
      "math",
      "symbols"
    ],
    version: "v19",
    lastModified: "2025-09-05",
    files: {
      regular: "https://fonts.gstatic.com/s/notosansglagolitic/v19/1q2ZY4-BBFBst88SU_tOj4J-4yuNF_HI4ERK4Amu7nM1.ttf"
    },
    category: "sans-serif",
    kind: "webfonts#webfont",
    menu: "https://fonts.gstatic.com/s/notosansglagolitic/v19/1q2ZY4-BBFBst88SU_tOj4J-4yuNF_HI4HRL6g0.ttf"
  },
  {
    family: "Shafarik",
    variants: [
      "regular"
    ],
    subsets: [
      "cyrillic",
      "cyrillic-ext",
      "glagolitic",
      "latin",
      "latin-ext"
    ],
    version: "v3",
    lastModified: "2025-05-30",
    files: {
      regular: "https://fonts.gstatic.com/s/shafarik/v3/RWmLoKaF7PojpZXlW52sbsHKqLkD.ttf"
    },
    category: "display",
    kind: "webfonts#webfont",
    menu: "https://fonts.gstatic.com/s/shafarik/v3/RWmLoKaF7PojpZXlW62tZMU.ttf"
  }
];

export default data;
