// This file is auto-generated by generateFontSubsetFiles.ts
import { GoogleFontItem } from "../types";

const data: GoogleFontItem[] = [
  {
    family: "Noto Sans Grantha",
    variants: ["regular"],
    subsets: ["grantha", "latin", "latin-ext"],
    version: "v20",
    lastModified: "2025-09-16",
    files: {
      regular: "https://fonts.gstatic.com/s/notosansgrantha/v20/3y976akwcCjmsU8NDyrKo3IQfQ4o-r8cFeulHc6N.ttf",
    },
    category: "sans-serif",
    kind: "webfonts#webfont",
    menu: "https://fonts.gstatic.com/s/notosansgrantha/v20/3y976akwcCjmsU8NDyrKo3IQfQ4o-o8dH-8.ttf",
  },
  {
    family: "Noto Serif Grantha",
    variants: ["regular"],
    subsets: ["grantha", "latin", "latin-ext"],
    version: "v22",
    lastModified: "2025-09-11",
    files: {
      regular: "https://fonts.gstatic.com/s/notoserifgrantha/v22/qkBIXuEH5NzDDvc3fLDYxPk9-Wq3WLiqFENLR7fHGw.ttf",
    },
    category: "serif",
    kind: "webfonts#webfont",
    menu: "https://fonts.gstatic.com/s/notoserifgrantha/v22/qkBIXuEH5NzDDvc3fLDYxPk9-Wq3WLiaFUlP.ttf",
  },
];

export default data;
