// This file is auto-generated by generateFontSubsetFiles.ts
import { GoogleFontItem } from "../types";

const data: GoogleFontItem[] = [
  {
    family: "Noto Sans Lydian",
    variants: ["regular"],
    subsets: ["latin", "latin-ext", "lydian"],
    version: "v19",
    lastModified: "2025-09-05",
    files: {
      regular:
        "https://fonts.gstatic.com/s/notosanslydian/v19/c4m71mVzGN7s8FmIukZJ1v4ZlcPReUPXMoIjEQI.ttf",
    },
    category: "sans-serif",
    kind: "webfonts#webfont",
    menu: "https://fonts.gstatic.com/s/notosanslydian/v19/c4m71mVzGN7s8FmIukZJ1v4ZlcPRSULdNg.ttf",
  },
];

export default data;
