// This file is auto-generated by generateFontSubsetFiles.ts
import { GoogleFontItem } from '../types';

const data: GoogleFontItem[] = [
  {
    family: "Noto Music",
    variants: [
      "regular"
    ],
    subsets: [
      "latin",
      "latin-ext",
      "music"
    ],
    version: "v21",
    lastModified: "2025-09-05",
    files: {
      regular: "https://fonts.gstatic.com/s/notomusic/v21/pe0rMIiSN5pO63htf1sxIteQB9Zra1U.ttf"
    },
    category: "sans-serif",
    kind: "webfonts#webfont",
    menu: "https://fonts.gstatic.com/s/notomusic/v21/pe0rMIiSN5pO63htf1sxEtaaAw.ttf"
  }
];

export default data;
