// This file is auto-generated by generateFontSubsetFiles.ts
import { GoogleFontItem } from "../types";

const data: GoogleFontItem[] = [
  {
    family: "Cardo",
    variants: ["regular", "italic", "700"],
    subsets: [
      "gothic",
      "greek",
      "greek-ext",
      "hebrew",
      "latin",
      "latin-ext",
      "old-italic",
      "runic",
    ],
    version: "v21",
    lastModified: "2025-09-08",
    files: {
      "700":
        "https://fonts.gstatic.com/s/cardo/v21/wlpygwjKBV1pqhND-aQR82JHaTBX.ttf",
      regular:
        "https://fonts.gstatic.com/s/cardo/v21/wlp_gwjKBV1pqiv_1oAZ2H5O.ttf",
      italic:
        "https://fonts.gstatic.com/s/cardo/v21/wlpxgwjKBV1pqhv93IQ73W5OcCk.ttf",
    },
    category: "serif",
    kind: "webfonts#webfont",
    menu: "https://fonts.gstatic.com/s/cardo/v21/wlp_gwjKBV1pqhv-3IQ.ttf",
  },
  {
    family: "Noto Sans Old Italic",
    variants: ["regular"],
    subsets: ["latin", "latin-ext", "old-italic"],
    version: "v18",
    lastModified: "2025-09-08",
    files: {
      regular:
        "https://fonts.gstatic.com/s/notosansolditalic/v18/TuGOUUFzXI5FBtUq5a8bh68BJxxEVam7tWlRdRhtCC4d.ttf",
    },
    category: "sans-serif",
    kind: "webfonts#webfont",
    menu: "https://fonts.gstatic.com/s/notosansolditalic/v18/TuGOUUFzXI5FBtUq5a8bh68BJxxEVam7tVlQfxw.ttf",
  },
];

export default data;
