// This file is auto-generated by generateFontSubsetFiles.ts
import { GoogleFontItem } from "../types";

const data: GoogleFontItem[] = [
  {
    family: "Noto Sans Sogdian",
    variants: ["regular"],
    subsets: ["latin", "latin-ext", "sogdian"],
    version: "v17",
    lastModified: "2025-09-11",
    files: {
      regular:
        "https://fonts.gstatic.com/s/notosanssogdian/v17/taiQGn5iC4--qtsfi4Jp6eHPnfxQBo--Pm6KHidM.ttf",
    },
    category: "sans-serif",
    kind: "webfonts#webfont",
    menu: "https://fonts.gstatic.com/s/notosanssogdian/v17/taiQGn5iC4--qtsfi4Jp6eHPnfxQBr-_NGo.ttf",
  },
];

export default data;
