// This file is auto-generated by generateFontSubsetFiles.ts
import { GoogleFontItem } from '../types';

const data: GoogleFontItem[] = [
  {
    family: "Noto Sans Tirhuta",
    variants: [
      "regular"
    ],
    subsets: [
      "latin",
      "latin-ext",
      "tirhuta"
    ],
    version: "v17",
    lastModified: "2025-09-05",
    files: {
      regular: "https://fonts.gstatic.com/s/notosanstirhuta/v17/t5t6IQYRNJ6TWjahPR6X-M-apUyby7uGUBsTrn5P.ttf"
    },
    category: "sans-serif",
    kind: "webfonts#webfont",
    menu: "https://fonts.gstatic.com/s/notosanstirhuta/v17/t5t6IQYRNJ6TWjahPR6X-M-apUyby4uHWh8.ttf"
  }
];

export default data;
