import { BaseColumn } from "@/types/table.type";

export const STUDENT_TABLE_COLUMNS: BaseColumn[] = [
    {
        id: "name",
        label: "الاسم",
        type: "text",
        accessor: "name",
        editable: true,
        sortable: true,
        filterable: true,
        resizable: true,
        widthStorageKey: "student_table_student_name_column_width",
    },
    {
        id: "email",
        label: "البريد الإلكتروني",
        type: "text",
        accessor: "email",
        editable: true,
        sortable: true,
        filterable: true,
        resizable: true,
        widthStorageKey: "student_table_student_email_column_width",
    },
    {
        id: "dateOfBirth",
        label: "تاريخ الميلاد",
        type: "date",
        accessor: "dateOfBirth",
        editable: true,
        sortable: true,
        filterable: true,
        resizable: true,
        widthStorageKey: "student_table_student_dateOfBirth_column_width",
    },
    {
        id: "gender",
        label: "الجنس",
        type: "select",
        accessor: "gender",
        editable: true,
        sortable: true,
        filterable: true,
        resizable: true,
        widthStorageKey: "student_table_student_gender_column_width",
        options: [
            { label: "ذكر", value: "Male" },
            { label: "أنثى", value: "Female" },
        ],
    },
    {
        id: "nationality",
        label: "الجنسية",
        type: "country",
        accessor: "nationality",
        editable: true,
        sortable: true,
        filterable: true,
        resizable: true,
        widthStorageKey: "student_table_student_nationality_column_width",
    },
    {
        id: "phoneNumber",
        label: "رقم الهاتف",
        type: "phone",
        accessor: "phoneNumber",
        sortable: false,
        filterable: true,
        editable: true,
        resizable: true,
        widthStorageKey: "student_table_student_phoneNumber_column_width",
    },
    {
        id: "createdAt",
        label: "تاريخ الإضافة",
        type: "date",
        accessor: "createdAt",
        sortable: true,
        filterable: true,
        editable: false,
        resizable: true,
        widthStorageKey: "student_table_student_createdAt_column_width",
    },
    {
        id: "updatedAt",
        label: "تاريخ التحديث",
        type: "date",
        accessor: "updatedAt",
        sortable: true,
        filterable: true,
        editable: false,
        resizable: true,
        widthStorageKey: "student_table_student_updatedAt_column_width",
    },
];
