import { CountryCode } from "@/client/graphql/generated/gql/graphql";
import { MuiTelInputCountry } from "mui-tel-input";

interface CountryType {
  code: CountryCode;
  phone: string;
  flag: string;
  suggested?: boolean;
}

export type { CountryType };

export const preferredCountries: MuiTelInputCountry[] = [
  "SA",
  "PS",
  "YE",
  "SY",
  "EG",
  "KW",
  "QA",
  "OM",
  "BH",
  "LB",
  "JO",
  "IQ",
  "LY",
  "AE",
  "TN",
  "DZ",
  "MA",
  "SD",
  "MR",
  "SO",
  "ID",
  "KM",
  "DJ",
  "ER",
  "SS",
  "EH",
];

// From https://bitbucket.org/atlassian/atlaskit-mk-2/raw/4ad0e56649c3e6c973e226b7efaeb28cb240ccb0/packages/core/select/src/data/countries.js
const countries: readonly CountryType[] = [
  { code: CountryCode.Sa, phone: "966", flag: "🇸🇦" },
  { code: CountryCode.Ps, phone: "970", flag: "🇵🇸" },
  { code: CountryCode.Ye, phone: "967", flag: "🇾🇪" },
  { code: CountryCode.Sy, phone: "963", flag: "🇸🇾" },
  { code: CountryCode.Eg, phone: "20", flag: "🇪🇬" },
  { code: CountryCode.Kw, phone: "965", flag: "🇰🇼" },
  { code: CountryCode.Qa, phone: "974", flag: "🇶🇦" },
  { code: CountryCode.Om, phone: "968", flag: "🇴🇲" },
  { code: CountryCode.Bh, phone: "973", flag: "🇧🇭" },
  { code: CountryCode.Lb, phone: "961", flag: "🇱🇧" },
  { code: CountryCode.Jo, phone: "962", flag: "🇯🇴" },
  { code: CountryCode.Iq, phone: "964", flag: "🇮🇶" },
  { code: CountryCode.Ly, phone: "218", flag: "🇱🇾" },
  { code: CountryCode.Ae, phone: "971", flag: "🇦🇪" },
  { code: CountryCode.Tn, phone: "216", flag: "🇹🇳" },
  { code: CountryCode.Dz, phone: "213", flag: "🇩🇿" },
  { code: CountryCode.Ma, phone: "212", flag: "🇲🇦" },
  { code: CountryCode.Sd, phone: "249", flag: "🇸🇩" },
  { code: CountryCode.Id, phone: "62", flag: "🇮🇩" },
  { code: CountryCode.Mr, phone: "222", flag: "🇲🇷" },
  { code: CountryCode.So, phone: "252", flag: "🇸🇴" },
  { code: CountryCode.Km, phone: "269", flag: "🇰🇲" },
  { code: CountryCode.Dj, phone: "253", flag: "🇩🇯" },
  { code: CountryCode.Er, phone: "291", flag: "🇪🇷" },
  { code: CountryCode.Ss, phone: "211", flag: "🇸🇸" },
  { code: CountryCode.Eh, phone: "212", flag: "🇪🇭" },
  { code: CountryCode.Ad, phone: "376", flag: "🇦🇩" },
  { code: CountryCode.Af, phone: "93", flag: "🇦🇫" },
  { code: CountryCode.Ag, phone: "1-268", flag: "🇦🇬" },
  { code: CountryCode.Ai, phone: "1-264", flag: "🇦🇮" },
  { code: CountryCode.Al, phone: "355", flag: "🇦🇱" },
  { code: CountryCode.Am, phone: "374", flag: "🇦🇲" },
  { code: CountryCode.Ao, phone: "244", flag: "🇦🇴" },
  { code: CountryCode.Aq, phone: "672", flag: "🇦🇶" },
  { code: CountryCode.Ar, phone: "54", flag: "🇦🇷" },
  { code: CountryCode.As, phone: "1-684", flag: "🇦🇸" },
  { code: CountryCode.At, phone: "43", flag: "🇦🇹" },
  { code: CountryCode.Au, phone: "61", flag: "🇦🇺" },
  { code: CountryCode.Aw, phone: "297", flag: "🇦🇼" },
  { code: CountryCode.Ax, phone: "358", flag: "🇦🇽" },
  { code: CountryCode.Az, phone: "994", flag: "🇦🇿" },
  { code: CountryCode.Ba, phone: "387", flag: "🇧🇦" },
  { code: CountryCode.Bb, phone: "1-246", flag: "🇧🇧" },
  { code: CountryCode.Bd, phone: "880", flag: "🇧🇩" },
  { code: CountryCode.Be, phone: "32", flag: "🇧🇪" },
  { code: CountryCode.Bf, phone: "226", flag: "🇧🇫" },
  { code: CountryCode.Bg, phone: "359", flag: "🇧🇬" },
  { code: CountryCode.Bi, phone: "257", flag: "🇧🇮" },
  { code: CountryCode.Bj, phone: "229", flag: "🇧🇯" },
  { code: CountryCode.Bl, phone: "590", flag: "🇧🇱" },
  { code: CountryCode.Bm, phone: "1-441", flag: "🇧🇲" },
  { code: CountryCode.Bn, phone: "673", flag: "🇧🇳" },
  { code: CountryCode.Bo, phone: "591", flag: "🇧🇴" },
  { code: CountryCode.Br, phone: "55", flag: "🇧🇷" },
  { code: CountryCode.Bs, phone: "1-242", flag: "🇧🇸" },
  { code: CountryCode.Bt, phone: "975", flag: "🇧🇹" },
  { code: CountryCode.Bv, phone: "47", flag: "🇧🇻" },
  { code: CountryCode.Bw, phone: "267", flag: "🇧🇼" },
  { code: CountryCode.By, phone: "375", flag: "🇧🇾" },
  { code: CountryCode.Bz, phone: "501", flag: "🇧🇿" },
  { code: CountryCode.Ca, phone: "1", flag: "🇨🇦" },
  { code: CountryCode.Cc, phone: "61", flag: "🇨🇨" },
  { code: CountryCode.Cd, phone: "243", flag: "🇨🇩" },
  { code: CountryCode.Cf, phone: "236", flag: "🇨🇫" },
  { code: CountryCode.Cg, phone: "242", flag: "🇨🇬" },
  { code: CountryCode.Ch, phone: "41", flag: "🇨🇭" },
  { code: CountryCode.Ci, phone: "225", flag: "🇨🇮" },
  { code: CountryCode.Ck, phone: "682", flag: "🇨🇰" },
  { code: CountryCode.Cl, phone: "56", flag: "🇨🇱" },
  { code: CountryCode.Cm, phone: "237", flag: "🇨🇲" },
  { code: CountryCode.Cn, phone: "86", flag: "🇨🇳" },
  { code: CountryCode.Co, phone: "57", flag: "🇨🇴" },
  { code: CountryCode.Cr, phone: "506", flag: "🇨🇷" },
  { code: CountryCode.Cu, phone: "53", flag: "🇨🇺" },
  { code: CountryCode.Cv, phone: "238", flag: "🇨🇻" },
  { code: CountryCode.Cw, phone: "599", flag: "🇨🇼" },
  { code: CountryCode.Cx, phone: "61", flag: "🇨🇽" },
  { code: CountryCode.Cy, phone: "357", flag: "🇨🇾" },
  { code: CountryCode.Cz, phone: "420", flag: "🇨🇿" },
  { code: CountryCode.De, phone: "49", flag: "🇩🇪" },
  { code: CountryCode.Dk, phone: "45", flag: "🇩🇰" },
  { code: CountryCode.Dm, phone: "1-767", flag: "🇩🇲" },
  { code: CountryCode.Do, phone: "1-809", flag: "🇩🇴" },
  { code: CountryCode.Ec, phone: "593", flag: "🇪🇨" },
  { code: CountryCode.Ee, phone: "372", flag: "🇪🇪" },
  { code: CountryCode.Es, phone: "34", flag: "🇪🇸" },
  { code: CountryCode.Et, phone: "251", flag: "🇪🇹" },
  { code: CountryCode.Fi, phone: "358", flag: "🇫🇮" },
  { code: CountryCode.Fj, phone: "679", flag: "🇫🇯" },
  { code: CountryCode.Fk, phone: "500", flag: "🇫🇰" },
  { code: CountryCode.Fm, phone: "691", flag: "🇫🇲" },
  { code: CountryCode.Fo, phone: "298", flag: "🇫🇴" },
  { code: CountryCode.Fr, phone: "33", flag: "🇫🇷" },
  { code: CountryCode.Ga, phone: "241", flag: "🇬🇦" },
  { code: CountryCode.Gb, phone: "44", flag: "🇬🇧" },
  { code: CountryCode.Gd, phone: "1-473", flag: "🇬🇩" },
  { code: CountryCode.Ge, phone: "995", flag: "🇬🇪" },
  { code: CountryCode.Gf, phone: "594", flag: "🇬🇫" },
  { code: CountryCode.Gg, phone: "44", flag: "🇬🇬" },
  { code: CountryCode.Gh, phone: "233", flag: "🇬🇭" },
  { code: CountryCode.Gi, phone: "350", flag: "🇬🇮" },
  { code: CountryCode.Gl, phone: "299", flag: "🇬🇱" },
  { code: CountryCode.Gm, phone: "220", flag: "🇬🇲" },
  { code: CountryCode.Gn, phone: "224", flag: "🇬🇳" },
  { code: CountryCode.Gp, phone: "590", flag: "🇬🇵" },
  { code: CountryCode.Gq, phone: "240", flag: "🇬🇶" },
  { code: CountryCode.Gr, phone: "30", flag: "🇬🇷" },
  { code: CountryCode.Gs, phone: "500", flag: "🇬🇸" },
  { code: CountryCode.Gt, phone: "502", flag: "🇬🇹" },
  { code: CountryCode.Gu, phone: "1-671", flag: "🇬🇺" },
  { code: CountryCode.Gw, phone: "245", flag: "🇬🇼" },
  { code: CountryCode.Gy, phone: "592", flag: "🇬🇾" },
  { code: CountryCode.Hk, phone: "852", flag: "🇭🇰" },
  { code: CountryCode.Hm, phone: "672", flag: "🇭🇲" },
  { code: CountryCode.Hn, phone: "504", flag: "🇭🇳" },
  { code: CountryCode.Hr, phone: "385", flag: "🇭🇷" },
  { code: CountryCode.Ht, phone: "509", flag: "🇭🇹" },
  { code: CountryCode.Hu, phone: "36", flag: "🇭🇺" },
  { code: CountryCode.Ie, phone: "353", flag: "🇮🇪" },
  { code: CountryCode.Im, phone: "44", flag: "🇮🇲" },
  { code: CountryCode.In, phone: "91", flag: "🇮🇳" },
  { code: CountryCode.Io, phone: "246", flag: "🇮🇴" },
  { code: CountryCode.Ir, phone: "98", flag: "🇮🇷" },
  { code: CountryCode.Is, phone: "354", flag: "🇮🇸" },
  { code: CountryCode.It, phone: "39", flag: "🇮🇹" },
  { code: CountryCode.Je, phone: "44", flag: "🇯🇪" },
  { code: CountryCode.Jm, phone: "1-876", flag: "🇯🇲" },
  { code: CountryCode.Jp, phone: "81", flag: "🇯🇵" },
  { code: CountryCode.Ke, phone: "254", flag: "🇰🇪" },
  { code: CountryCode.Kg, phone: "996", flag: "🇰🇬" },
  { code: CountryCode.Kh, phone: "855", flag: "🇰🇭" },
  { code: CountryCode.Ki, phone: "686", flag: "🇰🇮" },
  { code: CountryCode.Kn, phone: "1-869", flag: "🇰🇳" },
  { code: CountryCode.Kp, phone: "850", flag: "🇰🇵" },
  { code: CountryCode.Kr, phone: "82", flag: "🇰🇷" },
  { code: CountryCode.Ky, phone: "1-345", flag: "🇰🇾" },
  { code: CountryCode.Kz, phone: "7", flag: "🇰🇿" },
  { code: CountryCode.La, phone: "856", flag: "🇱🇦" },
  { code: CountryCode.Lc, phone: "1-758", flag: "🇱🇨" },
  { code: CountryCode.Li, phone: "423", flag: "🇱🇮" },
  { code: CountryCode.Lk, phone: "94", flag: "🇱🇰" },
  { code: CountryCode.Lr, phone: "231", flag: "🇱🇷" },
  { code: CountryCode.Ls, phone: "266", flag: "🇱🇸" },
  { code: CountryCode.Lt, phone: "370", flag: "🇱🇹" },
  { code: CountryCode.Lu, phone: "352", flag: "🇱🇺" },
  { code: CountryCode.Lv, phone: "371", flag: "🇱🇻" },
  { code: CountryCode.Mc, phone: "377", flag: "🇲🇨" },
  { code: CountryCode.Md, phone: "373", flag: "🇲🇩" },
  { code: CountryCode.Me, phone: "382", flag: "🇲🇪" },
  { code: CountryCode.Mf, phone: "590", flag: "🇲🇫" },
  { code: CountryCode.Mg, phone: "261", flag: "🇲🇬" },
  { code: CountryCode.Mh, phone: "692", flag: "🇲🇭" },
  { code: CountryCode.Mk, phone: "389", flag: "🇲🇰" },
  { code: CountryCode.Ml, phone: "223", flag: "🇲🇱" },
  { code: CountryCode.Mm, phone: "95", flag: "🇲🇲" },
  { code: CountryCode.Mn, phone: "976", flag: "🇲🇳" },
  { code: CountryCode.Mo, phone: "853", flag: "🇲🇴" },
  { code: CountryCode.Mp, phone: "1-670", flag: "🇲🇵" },
  { code: CountryCode.Mq, phone: "596", flag: "🇲🇶" },
  { code: CountryCode.Ms, phone: "1-664", flag: "🇲🇸" },
  { code: CountryCode.Mt, phone: "356", flag: "🇲🇹" },
  { code: CountryCode.Mu, phone: "230", flag: "🇲🇺" },
  { code: CountryCode.Mv, phone: "960", flag: "🇲🇻" },
  { code: CountryCode.Mw, phone: "265", flag: "🇲🇼" },
  { code: CountryCode.Mx, phone: "52", flag: "🇲🇽" },
  { code: CountryCode.My, phone: "60", flag: "🇲🇾" },
  { code: CountryCode.Mz, phone: "258", flag: "🇲🇿" },
  { code: CountryCode.Na, phone: "264", flag: "🇳🇦" },
  { code: CountryCode.Nc, phone: "687", flag: "🇳🇨" },
  { code: CountryCode.Ne, phone: "227", flag: "🇳🇪" },
  { code: CountryCode.Nf, phone: "672", flag: "🇳🇫" },
  { code: CountryCode.Ng, phone: "234", flag: "🇳🇬" },
  { code: CountryCode.Ni, phone: "505", flag: "🇳🇮" },
  { code: CountryCode.Nl, phone: "31", flag: "🇳🇱" },
  { code: CountryCode.No, phone: "47", flag: "🇳🇴" },
  { code: CountryCode.Np, phone: "977", flag: "🇳🇵" },
  { code: CountryCode.Nr, phone: "674", flag: "🇳🇷" },
  { code: CountryCode.Nu, phone: "683", flag: "🇳🇺" },
  { code: CountryCode.Nz, phone: "64", flag: "🇳🇿" },
  { code: CountryCode.Pa, phone: "507", flag: "🇵🇦" },
  { code: CountryCode.Pe, phone: "51", flag: "🇵🇪" },
  { code: CountryCode.Pf, phone: "689", flag: "🇵🇫" },
  { code: CountryCode.Pg, phone: "675", flag: "🇵🇬" },
  { code: CountryCode.Ph, phone: "63", flag: "🇵🇭" },
  { code: CountryCode.Pk, phone: "92", flag: "🇵🇰" },
  { code: CountryCode.Pl, phone: "48", flag: "🇵🇱" },
  { code: CountryCode.Pm, phone: "508", flag: "🇵🇲" },
  { code: CountryCode.Pn, phone: "870", flag: "🇵🇳" },
  { code: CountryCode.Pr, phone: "1", flag: "🇵🇷" },
  { code: CountryCode.Pt, phone: "351", flag: "🇵🇹" },
  { code: CountryCode.Pw, phone: "680", flag: "🇵🇼" },
  { code: CountryCode.Py, phone: "595", flag: "🇵🇾" },
  { code: CountryCode.Re, phone: "262", flag: "🇷🇪" },
  { code: CountryCode.Ro, phone: "40", flag: "🇷🇴" },
  { code: CountryCode.Rs, phone: "381", flag: "🇷🇸" },
  { code: CountryCode.Ru, phone: "7", flag: "🇷🇺" },
  { code: CountryCode.Rw, phone: "250", flag: "🇷🇼" },
  { code: CountryCode.Sb, phone: "677", flag: "🇸🇧" },
  { code: CountryCode.Sc, phone: "248", flag: "🇸🇨" },
  { code: CountryCode.Se, phone: "46", flag: "🇸🇪" },
  { code: CountryCode.Sg, phone: "65", flag: "🇸🇬" },
  { code: CountryCode.Sh, phone: "290", flag: "🇸🇭" },
  { code: CountryCode.Si, phone: "386", flag: "🇸🇮" },
  { code: CountryCode.Sj, phone: "47", flag: "🇸🇯" },
  { code: CountryCode.Sk, phone: "421", flag: "🇸🇰" },
  { code: CountryCode.Sl, phone: "232", flag: "🇸🇱" },
  { code: CountryCode.Sm, phone: "378", flag: "🇸🇲" },
  { code: CountryCode.Sn, phone: "221", flag: "🇸🇳" },
  { code: CountryCode.Sr, phone: "597", flag: "🇸🇷" },
  { code: CountryCode.St, phone: "239", flag: "🇸🇹" },
  { code: CountryCode.Sv, phone: "503", flag: "🇸🇻" },
  { code: CountryCode.Sx, phone: "1-721", flag: "🇸🇽" },
  { code: CountryCode.Sz, phone: "268", flag: "🇸🇿" },
  { code: CountryCode.Tc, phone: "1-649", flag: "🇹🇨" },
  { code: CountryCode.Td, phone: "235", flag: "🇹🇩" },
  { code: CountryCode.Tf, phone: "262", flag: "🇹🇫" },
  { code: CountryCode.Tg, phone: "228", flag: "🇹🇬" },
  { code: CountryCode.Th, phone: "66", flag: "🇹🇭" },
  { code: CountryCode.Tj, phone: "992", flag: "🇹🇯" },
  { code: CountryCode.Tk, phone: "690", flag: "🇹🇰" },
  { code: CountryCode.Tl, phone: "670", flag: "🇹🇱" },
  { code: CountryCode.Tm, phone: "993", flag: "🇹🇲" },
  { code: CountryCode.To, phone: "676", flag: "🇹🇴" },
  { code: CountryCode.Tr, phone: "90", flag: "🇹🇷" },
  { code: CountryCode.Tv, phone: "688", flag: "🇹🇻" },
  { code: CountryCode.Tw, phone: "886", flag: "🇹🇼" },
  { code: CountryCode.Tz, phone: "255", flag: "🇹🇿" },
  { code: CountryCode.Ua, phone: "380", flag: "🇺🇦" },
  { code: CountryCode.Ug, phone: "256", flag: "🇺🇬" },
  { code: CountryCode.Us, phone: "1", flag: "🇺🇸" },
  { code: CountryCode.Uy, phone: "598", flag: "🇺🇾" },
  { code: CountryCode.Uz, phone: "998", flag: "🇺🇿" },
  { code: CountryCode.Va, phone: "379", flag: "🇻🇦" },
  { code: CountryCode.Vc, phone: "1-784", flag: "🇻🇨" },
  { code: CountryCode.Ve, phone: "58", flag: "🇻🇪" },
  { code: CountryCode.Vg, phone: "1-284", flag: "🇻🇬" },
  { code: CountryCode.Vi, phone: "1-340", flag: "🇻🇮" },
  { code: CountryCode.Vn, phone: "84", flag: "🇻🇳" },
  { code: CountryCode.Vu, phone: "678", flag: "🇻🇺" },
  { code: CountryCode.Wf, phone: "681", flag: "🇼🇫" },
  { code: CountryCode.Ws, phone: "685", flag: "🇼🇸" },
  { code: CountryCode.Xk, phone: "383", flag: "🇽🇰" },
  { code: CountryCode.Yt, phone: "262", flag: "🇾🇹" },
  { code: CountryCode.Za, phone: "27", flag: "🇿🇦" },
  { code: CountryCode.Zm, phone: "260", flag: "🇿🇲" },
  { code: CountryCode.Zw, phone: "263", flag: "🇿🇼" },
];

export default countries;
