// This file is auto-generated by generateFontSubsetFiles.ts
import { GoogleFontItem } from '../types';

const data: GoogleFontItem[] = [
  {
    "family": "Noto Sans Carian",
    "variants": [
      "regular"
    ],
    "subsets": [
      "carian",
      "latin",
      "latin-ext"
    ],
    "version": "v17",
    "lastModified": "2025-09-05",
    "files": {
      "regular": "https://fonts.gstatic.com/s/notosanscarian/v17/LDIpaoiONgYwA9Yc6f0gUILeMIOgs7ob9yGLmfI.ttf"
    },
    "category": "sans-serif",
    "kind": "webfonts#webfont",
    "menu": "https://fonts.gstatic.com/s/notosanscarian/v17/LDIpaoiONgYwA9Yc6f0gUILeMIOgg7sR8w.ttf"
  }
];

export default data;
