// This file is auto-generated by generateFontSubsetFiles.ts
import { GoogleFontItem } from '../types';

const data: GoogleFontItem[] = [
  {
    "family": "Noto Sans Mongolian",
    "variants": [
      "regular"
    ],
    "subsets": [
      "latin",
      "latin-ext",
      "math",
      "mongolian",
      "symbols"
    ],
    "version": "v23",
    "lastModified": "2025-09-16",
    "files": {
      "regular": "https://fonts.gstatic.com/s/notosansmongolian/v23/VdGCAYADGIwE0EopZx8xQfHlgEAMsrToxLsg6-av1x0.ttf"
    },
    "category": "sans-serif",
    "kind": "webfonts#webfont",
    "menu": "https://fonts.gstatic.com/s/notosansmongolian/v23/VdGCAYADGIwE0EopZx8xQfHlgEAMsrTo9Loq7w.ttf"
  }
];

export default data;
