// This file is auto-generated by generateFontSubsetFiles.ts
import { GoogleFontItem } from '../types';

const data: GoogleFontItem[] = [
  {
    "family": "Noto Serif Ottoman Siyaq",
    "variants": [
      "regular"
    ],
    "subsets": [
      "latin",
      "latin-ext",
      "ottoman-siyaq-numbers"
    ],
    "version": "v2",
    "lastModified": "2025-05-30",
    "files": {
      "regular": "https://fonts.gstatic.com/s/notoserifottomansiyaq/v2/fC1yPZ9IYnzRhTrrc4s8cSvYI0eozzaFOQ01qoHLJrgA00kAdA.ttf"
    },
    "category": "serif",
    "kind": "webfonts#webfont",
    "menu": "https://fonts.gstatic.com/s/notoserifottomansiyaq/v2/fC1yPZ9IYnzRhTrrc4s8cSvYI0eozzaFOQ01qoH7J7IE.ttf"
  }
];

export default data;
