import { gql } from '@apollo/client';

export const CREATE_TEMPLATE = gql`
mutation createTemplate($input: CreateTemplateInput!){
    createTemplate(input: $input){
        category{
            categorySpecialType
            childCategories{
                categorySpecialType
                childCategories{
                    categorySpecialType
                    createdAt
                    description
                    id
                    name
                    order
                    parentCategory{
                        categorySpecialType
                        childCategories{
                            categorySpecialType
                            createdAt
                            description
                            id
                            name
                            order
                            updatedAt
                        }
                        createdAt
                        description
                        id
                        name
                        order
                        parentCategory{
                            categorySpecialType
                            createdAt
                            description
                            id
                            name
                            order
                            updatedAt
                        }
                        updatedAt
                    }
                    updatedAt
                }
                createdAt
                description
                id
                name
                order
                updatedAt
            }
            createdAt
            description
            id
            name
            order
            parentCategory{
                categorySpecialType
                createdAt
                description
                id
                name
                order
                updatedAt
            }
            updatedAt
        }
        createdAt
        description
        id
        imageUrl
        name
        order
        preSuspensionCategory{
            categorySpecialType
            childCategories{
                categorySpecialType
                createdAt
                description
                id
                name
                order
                updatedAt
            }
            createdAt
            description
            id
            name
            order
            parentCategory{
                categorySpecialType
                createdAt
                description
                id
                name
                order
                updatedAt
            }
            updatedAt
        }
        updatedAt
    }
}
`;
